SOURCE/Historical/Controllers/ListController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Historical.Models;
using Historical.Business;

namespace Historical.Controllers
{
    public class ListController : Controller
    {
        ListBusiness listBusiness = new ListBusiness();
        private IStoreRepository repository;
        public int Pagesize = 12;
        public ListController(IStoreRepository repo)
        {
            repository = repo;
        }
        public IActionResult Index(int RelicPage = 1) => View(
            new RelicListViewModel {
                Relics = repository.relics

                .OrderBy(p => p.Id).Skip((RelicPage - 1) * Pagesize)
                .Take(Pagesize),
                Pageinfo = new PageInfo
                {
                    CurrentPage = RelicPage,
                    ItemsPage = Pagesize,
                    TotalItems = repository.relics.Count()
                },

            });
    
       public PartialViewResult Detail(int ID)
        {
            try
            {
                var data = listBusiness.Detail(ID);
                return PartialView("ListDetail",data);
            }
            catch(Exception e)
            {
                return null;
            }
        } 
    }
    
}

SOURCE/Historical/Views/List/Detail.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model RelicsOutputModel

<div>
    <!--? Hero Start -->
    <div class="slider-area2 ">
        <div class="slider-height2 hero-overly d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero__caption hero__caption2">
                            <h2>Services</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Hero End -->
    <!--? services area start -->

    <section class="services-section section-padding30 fix">
        <div class="container">

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="single-cat mb-40">
                        <div class="cat-icon">

                            <img src="@Model.ImageUrl" alt="">
                        </div>
                        <div class="cat-cap">
                            <h5><a>@Model.RelicsName</a></h5>
                            <p>@Model.Address</p>
                        </div>
                    </div>
                </div>
                <div>
                    <a href="@Model.MapUrl"></a>
                </div>
            </div>
        </div>
    </section>
</div>

SOURCE/Historical/Views/List/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model RelicListViewModel
<div>
    <!--? Hero Start -->
    <div class="slider-area2 ">
        <div class="slider-height2 hero-overly d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero__caption hero__caption2">
                            <h2>Services</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Hero End -->
    <!--? services area start -->
    <div id="data">        
        <section class="services-section section-padding30 fix" id="list">
            <div class="container">

                <div class="row">

                    @foreach (var list in Model.Relics)
                    {
                        <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="single-cat mb-40">
                                <div class="cat-icon">

                                    <img src="@list.ImageUrl" alt="">
                                </div>
                                <div class="cat-cap">
                                    <h5><a href="">@list.Name</a></h5>
                                    <p>@list.Address</p>
                                </div>
                                <button class="btn btn-danger" onclick="Detail(@list.Id)">Xem chi tiết</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div page-model="@Model.Pageinfo" page-ation="Index" page-class="btn" page-class-normal="btn-outline-dark"
                 page-class-selected="btn-primary">
            </div>
        </section>
    </div>
    
</div>
<script type="text/javascript">
    function Detail(id) {
        $.ajax({
            url: '@Url.Action("Detail","List")',
            data: { ID: id},
            type: 'POST',
            success: function (res) {
                $('#data').html(res);
            }
        });
    }
</script>

SOURCE/Historical/Views/List/ListDetail.cshtml
@*@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}*@
@model RelicsOutputModel

<div>
    <section class="services-section section-padding30 fix">
        <div class="container">
            <h1>Đây là chi tiết</h1>
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="single-cat mb-40">
                        <div class="cat-icon">

                            <img src="@Model.ImageUrl" alt="">
                        </div>
                        <div class="cat-cap">
                            <h5><a href="">@Model.RelicsName</a></h5>
                            <p>@Model.Address</p>
                        </div>
                    </div>
                </div>
                <div>
                    <a href="@Model.MapUrl"></a>
                </div>
            </div>
        </div>
    </section>
</div>