SOURCE/Historical/Controllers/Login_AdminController.cs
using Historical.Business;
using Historical.Model;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Historical.Controllers
{
    public class Login_AdminController : Controller
    {
        UserBusiness UserBusiness = new UserBusiness(); 
        public PartialViewResult Index()
        {
            return PartialView("_Login");
        }
        public User Login(string User_Name, string Pasword)
        {
            try
            {
                if (User_Name != null && Pasword != null)
                {
                    var data = UserBusiness.Login(User_Name, Pasword);
                    return data;
                }                
                return new User();
            }
            catch
            {
                return new User();
            }
        }
    }
}

SOURCE/Historical/Views/Login_Admin/_Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>ĐÔNG Y</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/slicknav.css">
    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/progressbar_barfiller.css">
    <link rel="stylesheet" href="~/css/gijgo.css">
    <link rel="stylesheet" href="~/css/animate.min.css">
    <link rel="stylesheet" href="~/css/animated-headline.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/css/slick.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body style="background: #f0f0f0;">
    @*<div class="divLoading" style="display: none">
            <img class="spinner" src="~/Content/images/index.rotate-pie-preloader-gif.svg" />
        </div>*@
    <div class="bg-image"></div>
    <div class="bg-text" style="height:520px;">
        <div class="col-md-12 px-0">
            <img src="~/Content/images/logoDongY.png" class="mt-3 mb-5" style="height:200px;width:auto;" />
        </div>
        <div class="txtLogin row mt-3" id="txtLogin">
            <div class="col-md-12 col-12">
                <input type="text" class="form-control col-md-12 inputLogin" placeholder="Tài khoản" id="txtUsernameLogin" name="">
                <i class="iconUsernameLogin fa fa-user-o mt-1" style="color:black; position:absolute; right:25px;top:9px"></i>
            </div>
        </div>
        <div class="txtLogin row mt-1" id="txtLogin">
            <div class="col-md-12 col-12">
                <input type="password" class="form-control col-md-12 inputLogin" placeholder="Mật khẩu" id="txtPasswordLogin" name="">
                <i class="iconPasswordLogin fa fa-unlock-alt mt-1" style="color:black; position:absolute; right:25px;top:9px"></i>
            </div>
        </div>
        <button class="col-md-12 btn btn-default mt-3 btnLogin" id="btnLogin" onclick="Login()">ĐĂNG NHẬP</button>
    </div>
    <script src="~/js/vendor/modernizr-3.5.0.min.js"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="~/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <!-- Jquery Mobile Menu -->
    <script src="~/js/jquery.slicknav.min.js"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/slick.min.js"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="~/js/wow.min.js"></script>
    <script src="~/js/animated.headline.js"></script>
    <script src="~/js/jquery.magnific-popup.js"></script>

    <!-- Date Picker -->
    <script src="~/js/gijgo.min.js"></script>
    <!-- Nice-select, sticky -->
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>
    <!-- Progress -->
    <script src="~/js/jquery.barfiller.js"></script>

    <!-- counter , waypoint,Hover Direction -->
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/waypoints.min.js"></script>
    <script src="~/js/jquery.countdown.min.js"></script>
    <script src="~/js/hover-direction-snake.min.js"></script>

    <!-- contact js -->
    <script src="~/js/contact.js"></script>
    <script src="~/js/jquery.form.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/mail-script.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="~/js/plugins.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>

<script type="text/javascript">
    function Login() {
        var user_name = $("#txtUsernameLogin").val();
        var pasword = $("#txtPasswordLogin").val();
        if (user_name === "" || pasword === "") {
            alert("Nhập đầy đủ thông tin");
        } else {
            $.ajax({
                url: '@Url.Action("Login","Login_Admin")',
                data: { User_Name: user_name, Pasword: pasword },
                type: 'POST',
                success: function (res) {
                    if (res != null) {
                        location.href = '/BackEndHome';
                    } else {
                        alert("Đăng nhập thất bại !");
                    }
                }
            });
        }
    };

</script>